=== LuisMiguelAlmeida/POO/Entrega/TESTS/simulation.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT simulation (grid, initialpoint, finalpoint, specialcostzones, obstacles, events)>
<!ATTLIST simulation finalinst CDATA #REQUIRED>
<!ATTLIST simulation initpop CDATA #REQUIRED>
<!ATTLIST simulation maxpop CDATA #REQUIRED>
<!ATTLIST simulation comfortsens CDATA #REQUIRED>
<!ELEMENT grid EMPTY>
<!ATTLIST grid colsnb CDATA #REQUIRED>
<!ATTLIST grid rowsnb CDATA #REQUIRED>
<!ELEMENT specialcostzones (zone?)>
<!ATTLIST specialcostzones num CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone xinitial CDATA #REQUIRED>
<!ATTLIST zone yinitial CDATA #REQUIRED>
<!ATTLIST zone xfinal CDATA #REQUIRED>
<!ATTLIST zone yfinal CDATA #REQUIRED>
<!ELEMENT obstacles (obstacle?)>
<!ATTLIST obstacles num CDATA #IMPLIED>
<!ELEMENT obstacle EMPTY>
<!ATTLIST obstacle xpos CDATA #REQUIRED>
<!ATTLIST obstacle ypos CDATA #REQUIRED>
<!ELEMENT events (death, reproduction, move)>
<!ELEMENT death  EMPTY>
<!ATTLIST death param CDATA #REQUIRED>
<!ELEMENT reproduction EMPTY>
<!ATTLIST reproduction param CDATA #REQUIRED>
<!ELEMENT move EMPTY>
<!ATTLIST move param CDATA #REQUIRED>

=== LuisMiguelAlmeida/POO/POO/POO/test_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE simulation SYSTEM "simulation.dtd"> 
<simulation finalinst="100" initpop="10" maxpop="500" comfortsens="3"> 
   <grid colsnb="5" rowsnb="4"/> 
   <initialpoint xinitial="1" yinitial="1"/> 
   <finalpoint xfinal="5" yfinal="4"/>
   <specialcostzones num="1">
      <zone xinitial="2" yinitial="2" xfinal="3" yfinal="3">4</zone>
   </specialcostzones>
   <obstacles num="4">
      <obstacle xpos="2" ypos="1"/>
      <obstacle xpos="2" ypos="3"/>
      <obstacle xpos="2" ypos="4"/>
      <obstacle xpos="4" ypos="2"/>
   </obstacles>
   <events>
      <death param="10"/>
      <reproduction param="1"/>
      <move param="1"/>
   </events>
</simulation>
